<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Add a human-readable booking `code` (e.g. EZT-2026-0001) to the bookings
     * table and backfill it for every existing row using each booking's own
     * creation year + zero-padded id, matching the format generated by the
     * Booking model's booted() hook for new bookings.
     */
    public function up(): void
    {
        Schema::table('bookings', function (Blueprint $table): void {
            $table->string('code', 20)->nullable()->unique()->after('id');
        });

        // Backfill per-row so the year reflects the booking's actual creation.
        DB::statement(
            "UPDATE bookings
             SET code = CONCAT('EZT-', YEAR(created_at), '-', LPAD(id, 4, '0'))
             WHERE code IS NULL"
        );
    }

    public function down(): void
    {
        Schema::table('bookings', function (Blueprint $table): void {
            $table->dropColumn('code');
        });
    }
};
